spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:mysql://localhost:3306/kodeecom   # changed from mysql → localhost
    username: root
    password: Nikhil@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka   # changed from eurekaservice
    register-with-eureka: true
    fetch-registry: true

feign:
  hystrix:
    enabled: true

spring:
  data:
    redis:
      host: unique-goldfish-27574.upstash.io
      port: 6379
      username: default
      password: AWu2AAIncDE3MmExYzNiMzNmZmQ0NDBmOTU4YWRjYWIzNWQ1YzJjMnAxMjc1NzQ
      ssl:
        enabled: true
